# Basic functions in Python

In [2]:
print("Hello AIML batch Nov 2025")

Hello AIML batch Nov 2025


In [3]:
x = 3
y = "Shivam"
print(x)
print(y)

3
Shivam


In [4]:
type(x)

int

In [5]:
type(y)

str

# Let's talk about list in Python.

In [6]:
students = [1, 2, 3 ,4, 5]

In [7]:
print(type(students))

<class 'list'>


In [8]:
x = [1, 'python', 'siri', True]
x

[1, 'python', 'siri', True]

# Numpy package

In [9]:
!pip install numpy

In [10]:
import numpy as np # np is here an alias


In [11]:
votes = np.array([1, 2, 3])
votes

array([1, 2, 3])

In [12]:
print(type(votes))


<class 'numpy.ndarray'>


In [13]:
import time

start = time.time()

time.sleep(2)

end = time.time()

print(end - start)

2.0014255046844482


In [14]:
a = 5
b = 10

In [15]:
import time

start = time.time()

c = a + b

end = time.time()

print(end - start)

0.0


In [16]:
start

1762598121.5905461

In [17]:
time.time() # no of seconds, passed since Jan 1, 1970

1762598121.6141284

In [18]:
1762532312.265586 / (60 * 60 * 24 * 365)

55.88953298660534

In [19]:
time.time()

1762598121.640934

In [20]:
# [0, 1, 2. ... 10]
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
# design an experiment to find out how much faster is numpy compared to python list

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
sum([1, 2, 3])

6

In [24]:
# 0 to 1 million

large_list = list(range(1000000))
large_array = np.arange(1000000)

start = time.time()
sum_list = sum(large_list)
end = time.time()

list_time = end - start


start = time.time()
sum_array = np.sum(large_array)
end = time.time()

array_time = end - start

print(list_time, array_time)

0.03199481964111328 0.0


In [25]:
list_time/array_time

ZeroDivisionError: float division by zero

# Let's explore homogenous-ness of numpy array

In [ ]:
np.array(list(range(10)))


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.shape # no of elements in the 1D array

(10,)

In [ ]:
b = np.array([[1,2,3],[4,5,6]]) #matrix
b.shape

(2, 3)

In [26]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

[False  True False  True]


In [30]:
import numpy as np
def rotate_img(mat):
    '''mat -> A 2d numpy array
       output -> A 2d numpy array is expected to be returned'''

    # YOUR CODE GOES HERE
    b = np.transpose(a)
    return b

a = np.array([[1,2,3],[4,5,6]])
rotate_img(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]
